[build]
  command = "yarn build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["messages/fa.json", "messages/en.json"]
